---
- name: Configure Personal VPS
  hosts: vps
  become: true
  vars_files:
    - "{{ playbook_dir }}/../../secrets.yml"
  roles:
    - { role: common, tags: ['common'] }
    - { role: security, tags: ['security'] }
    - { role: docker, tags: ['docker'] }
    - { role: authelia, tags: ['authelia'] }
    - { role: projects, tags: ['projects'] }
    - { role: personal-website, tags: ['personal-website'] }
    - { role: wishlist, tags: ['wishlist'] }
    - { role: coturn, tags: ['coturn'] }
    - { role: briefing, tags: ['briefing'] }
    - { role: xray-portal, tags: ['tunnel'] }
    - { role: caddy, tags: ['caddy'] }
    - { role: monitoring, tags: ['monitoring'] }